import 'dart:io';
import 'package:path/path.dart' as p;

import '../services/di_registrar.dart';
import '../services/feature_validator.dart';
import '../services/file_service.dart';
import '../template_engine/template_context.dart';
import '../template_engine/template_engine.dart';
import '../utils/case_converter.dart';

class FeatureGenerationResult {
  final bool wasCancelled;
  final List<String> writtenFiles;
  final List<String> skippedExistingFiles;

  /// Result of attempting to register the feature's repository into
  /// `service_locator.dart`. Null only when [wasCancelled] is true (a
  /// cancelled generation never touches DI).
  final DiRegistrationResult? diResult;

  /// Post-generation validation issues (missing files, leaked `.tmpl`,
  /// unresolved placeholders, missing/duplicate DI registration). Empty
  /// when [wasCancelled] is true.
  final List<ValidationIssue> validationIssues;

  const FeatureGenerationResult({
    required this.wasCancelled,
    required this.writtenFiles,
    required this.skippedExistingFiles,
    this.diResult,
    this.validationIssues = const [],
  });

  bool get isValid =>
      !validationIssues.any((i) => i.severity == ValidationSeverity.error);
}

/// Generates `lib/features/<feature>/{cubit,repository,model,presentation}`
/// for an existing Flutter project, following the Cubit + Repository +
/// GetIt conventions used throughout the rest of the generated app —
/// then automatically registers the new repository in
/// `lib/core/di/service_locator.dart` and validates the result.
class FeatureGenerator {
  final ConflictAction Function(String featureName) onExistingFeature;

  /// The `templates/` directory to read the `feature/` template from.
  /// Required (not resolved internally with a default) because locating
  /// it is inherently asynchronous — see `PackagePaths.resolveTemplatesRoot`
  /// — so the caller (`GenerateCommand.run()`, already `async`) resolves
  /// it once and passes it in. Tests pass a known directory directly.
  final Directory templatesRoot;

  final DiRegistrar diRegistrar;
  final FeatureValidator validator;

  FeatureGenerator({
    required this.onExistingFeature,
    required this.templatesRoot,
    this.diRegistrar = const DiRegistrar(),
    this.validator = const FeatureValidator(),
  });

  FeatureGenerationResult generate({
    required Directory projectRoot,
    required String featureName,
    required String packageName,
  }) {
    final context = TemplateContext.forFeature(
      featureName: featureName,
      packageName: packageName,
    );
    final engine = TemplateEngine(context);
    final fileService = FileService(engine);

    final templateDir = Directory(p.join(templatesRoot.path, 'feature'));
    // Features live under lib/features/<name>/ — the same convention the
    // auth flow (generated by `create`) already uses, so every feature in
    // the app (framework-provided or user-generated) lives in one place.
    final destinationRoot =
        Directory(p.join(projectRoot.path, 'lib', 'features'));

    final plannedPaths = fileService.planOutputPaths(templateDir);
    final alreadyExists = plannedPaths.any(
      (relative) => File(p.join(destinationRoot.path, relative)).existsSync(),
    );

    var conflictAction = ConflictAction.overwrite;
    if (alreadyExists) {
      conflictAction = onExistingFeature(featureName);
      if (conflictAction == ConflictAction.cancel) {
        return const FeatureGenerationResult(
          wasCancelled: true,
          writtenFiles: [],
          skippedExistingFiles: [],
        );
      }
    }

    final written = fileService.renderTree(
      templateRoot: templateDir,
      destinationRoot: destinationRoot,
      onConflict: conflictAction,
    );

    final writtenRelative = written
        .map((full) => p.relative(full, from: destinationRoot.path))
        .toSet();
    final skipped = plannedPaths
        .where((relative) => !writtenRelative.contains(relative))
        .toList();

    final nameCase = NameCase.from(featureName);
    final repositoryClassName = '${nameCase.pascal}Repository';
    // From lib/core/di/service_locator.dart to
    // lib/features/<name>/repository/<name>_repository.dart.
    final repositoryImportPath =
        '../../features/${nameCase.snake}/repository/${nameCase.snake}_repository.dart';
    final serviceLocatorFile = File(
      p.join(projectRoot.path, 'lib', 'core', 'di', 'service_locator.dart'),
    );

    final diResult = diRegistrar.registerRepository(
      serviceLocatorFile: serviceLocatorFile,
      repositoryClassName: repositoryClassName,
      importPath: repositoryImportPath,
    );

    final validation = validator.validate(
      destinationRoot: destinationRoot,
      featureNameSnake: nameCase.snake,
      expectedRelativePaths: plannedPaths,
      serviceLocatorFile: serviceLocatorFile,
      repositoryClassName: repositoryClassName,
      repositoryImportPath: repositoryImportPath,
    );

    return FeatureGenerationResult(
      wasCancelled: false,
      writtenFiles: written,
      skippedExistingFiles: skipped,
      diResult: diResult,
      validationIssues: validation.issues,
    );
  }
}
